#!/usr/bin/env bash
# This script displays only the following fields from /etc/passwd
# username, groupid, shell full path

while IFS=: read -r username _ uid _ _ home _; do
    echo "$line" | cut -d':' -f 1,3,6
done < /etc/passwd
