#!/usr/bin/env bash
# This script displays only the following fields from /etc/passwd
# username, groupid, shell full path

while IFS=: read -r username _ uid _ _ home _; do
    # Print username, user ID, and home directory
    echo "$username:$uid:$home"    
done < /etc/passwd
