#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
#   Displays hours from 0 to 12
#   Displays minuts from 1 to 59

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -lt 60 ]
    do
	echo "$minutes"
	((minutes++))
    done
    ((hour++))
done
